### ISSUE TITLE
Snapshot results in Arithmetic overflow error

### ISSUE THREAD

**Issue by kim0** [JocaPC/qpi#2] opened 2019-07-06 20:58 UTC
I'm a SQL newbie, so I hope it's not my mistake. I'm on Azure SQL Managed Instance.
```
1> EXEC qpi.snapshot_file_stats;
2> go
Msg 8115, Level 16, State 2, Server mssqlmi-stg.c3890485fa89.database.windows.net, Procedure qpi.snapshot_file_stats, Line 5
Arithmetic overflow error converting expression to data type int.
The statement has been terminated.
```
Regards

**Comment by JocaPC** [comment] 2019-07-25 18:56
Hi,

Thank you for reporting this. I'm struggling to reproduce this because it seems like some overflow caused by some large value. Is there a chance to execute parts of the procedure and find what column is failing? Could you try executing just this script:


```
SELECT db_name = DB_NAME(vfs.database_id),vfs.database_id,
		file_name = [mf].[name],size_gb = 8 * mf.size /1024/ 1024,[vfs].[file_id],
		[io_stall_read_ms],[io_stall_write_ms],[io_stall_queued_read_ms],[io_stall_queued_write_ms],[io_stall],
		[num_of_bytes_read], [num_of_bytes_written],
		[num_of_reads], [num_of_writes]
	FROM sys.dm_io_virtual_file_stats (db_id(@db_name),NULL) AS [vfs]
	JOIN sys.master_files AS [mf] ON
		[vfs].[database_id] = [mf].[database_id] AND [vfs].[file_id] = [mf].[file_id]
```
Some value is long but I cannot detect it based on my databases. I could convert all int columns to bigint but this would be a hammer solution.

**Comment by JocaPC** [comment] 2019-07-25 19:03
I made a change and changed interval_mi to be bigint and used DATEDIFF_BIG instead of DATEDIFF. This is the only possible place where int overflow issue might occur. Please try with the new version.

**Comment by JocaPC** [comment] 2019-08-21 17:13
@kim0 - I made several changed in the script where this error can happen. I cannot reproduce it on my database. I'm closing this issue and feel free to re-open it if it happens with the latest version.

**Closed as completed by JocaPC** 2019-08-21 17:13 UTC
Labels: bug, help wanted, good first issue
